### PR TITLE
Remove connect() to deleteLater() when running displayScript the firs…

### PR DESCRIPTION
**Pull request by madsl**
…t time so it doesn't get deleted after first run. Makes Xsetup script work again.

### CODE REVIEW

**Comment by madsl** [comment]
This fixes issue #919

**Comment by davidedmundson** [comment]
How is it any different?

**Comment by madsl** [comment]
I'm guessing it's because the finished() slot fires before kill() is called the second time.

**Comment by davidedmundson** [comment]
That would rely on the script finishing, and waitForFinish returning false because it hasn't finished. 
That can't happen.

**Comment by madsl** [comment]
With the patch, from journalctl:
```
nov. 29 21:10:02 latentcall sddm[11258]: Initializing...
nov. 29 21:10:02 latentcall sddm[11258]: Logind interface found
nov. 29 21:10:02 latentcall sddm[11258]: Starting...
nov. 29 21:10:02 latentcall sddm[11258]: Adding new display on vt 1 ...
nov. 29 21:10:02 latentcall sddm[11258]: Loading theme configuration from ""
nov. 29 21:10:02 latentcall sddm[11258]: Display server starting...
nov. 29 21:10:02 latentcall sddm[11258]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{2b2398fd-daa6-460b-9c0a-394cc5331706} -background none -noreset -displayfd 18 -seat seat0 vt1
nov. 29 21:10:03 latentcall sddm[11258]: Setting default cursor
nov. 29 21:10:03 latentcall sddm[11258]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
nov. 29 21:10:04 latentcall sddm[11258]: Display server started.
nov. 29 21:10:04 latentcall sddm[11258]: Socket server starting...
nov. 29 21:10:04 latentcall sddm[11258]: Socket server started.
nov. 29 21:10:04 latentcall sddm[11258]: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
nov. 29 21:10:04 latentcall sddm[11258]: Greeter starting...
```
Without the patch, from journalctl:
```
nov. 29 16:26:14 latentcall sddm[487]: Initializing...
nov. 29 16:26:14 latentcall sddm[487]: Logind interface found
nov. 29 16:26:14 latentcall sddm[487]: Starting...
nov. 29 16:26:14 latentcall sddm[487]: Adding new display on vt 1 ...
nov. 29 16:26:14 latentcall sddm[487]: Loading theme configuration from ""
nov. 29 16:26:14 latentcall sddm[487]: Display server starting...
nov. 29 16:26:14 latentcall sddm[487]: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{8c28fc1d-a6df-4879-b77a-dd95567065f2} -background none -noreset -displayfd 18 -seat seat0 vt1
nov. 29 16:26:15 latentcall sddm[487]: Setting default cursor
nov. 29 16:26:16 latentcall sddm[487]: Could not setup default cursor
nov. 29 16:26:16 latentcall sddm[487]: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
nov. 29 16:26:16 latentcall sddm[487]: QProcess::start: Process is already running
nov. 29 16:26:16 latentcall sddm[487]: Display server started.
nov. 29 16:26:16 latentcall sddm[487]: Socket server starting...
nov. 29 16:26:16 latentcall sddm[487]: Socket server started.
nov. 29 16:26:16 latentcall sddm[487]: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
nov. 29 16:26:16 latentcall sddm[487]: Greeter starting...
```

As you can see, you get the message "QProcess::start: Process is already running", so either there's a race condition somewhere when you use connect, or it is something else that I don't see... Either way, just cleaning up manually without using a finished() slot seemed to fix the issue.

**Comment by davidedmundson** [comment]
If we don't know what's causing something then we can't be sure if you've actually fixed anything.

----------------------

However, I think I see the bug:

We start xsetroot

we know that times out

we do               displayScript->kill(); 

This is *not atomic*. It just calls kill from stdlib.

We don't wait for finished after killing.

we start the second script

we connect

now the first script finishes <-- our "race"

That messes up everything

------

I think that means this patch isn't ideal.

Can you change this to be two different QProcess objects for the two scripts. It'd fix your issue and be a hundred times cleaner.

**Comment by davidedmundson** [comment]
Thanks.
if you can squash that into 1 commit I'll merge it.

**Comment by madsl** [comment]
Had to create a new pull request for it, #946.

**Pull request closed without merging**
