### PR TITLE
If autologin is used, avoid starting a display server for the greeter

### PR DESCRIPTION
**Pull request by Vogtinator**
Introduce a new "early autologin" path that starts the session without
starting the display server first. This avoids starting a rootful X just
to then ignore it and start a Wayland session in a separate VT.

This should avoid the race condition causing tty opening failures with wayland autologin, which is actually separate from #1844. In the autologin case, SDDM first starts the display server, which switches to e.g. tty2, then starts the user session which then picks e.g. tty1 which is about to be used by getty.

Needed some refactoring of Display.cpp. It's split into various small commits, should be simple to read individually.

I think I tested all possible combinations:
- [x] `DisplayServer=x11` + autologin into `plasmawayland`
- [x] `DisplayServer=x11` + autologin into `plasma6` (x11)
- [x] `DisplayServer=x11` + failed autologin (invalid user) into `plasma6` (x11)
- [x] `DisplayServer=x11` + failed autologin (invalid user) into `plasmawayland`
- [x] `DisplayServer=x11-user` + autologin into `plasmawayland`
- [x] `DisplayServer=wayland` + autologin into `plasma6`

All of those cases behaved as expected.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Does this affect when you do logout from an autologin session?

**Comment by Vogtinator** [comment]
> Does this affect when you do logout from an autologin session?

Not meaningfully. With this PR it no longer has to stop the zombie X for the greeter anymore before starting the next greeter. (Same as with #1968 for the non-autologin case.)

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
The code looks good to me, but this needs to be rebased to fix the CI.

**Comment by Vogtinator** [comment]
Meh, now TW failed because https://build.opensuse.org/request/show/1191331 didn't get published yet.

**Comment by buzzmandt** [comment]
What is the status on this please? I think this might fix my autologin landing in a tty1 issue.

**Comment by Vogtinator** [comment]
Ready to merge, waiting for @aleixpol and/or @davidedmundson

**Comment by davidedmundson** [comment]
If we switch the default to x11-user, which we should definitely do, do we not get all of this effectively for free without any new code?

Given we want to throw rootful mode away, we should avoid adding any other complexity unless there's a user-facing benefit.

**Comment by Vogtinator** [comment]
> Given we want to throw rootful mode away, we should avoid adding any other complexity unless there's a user-facing benefit.

Yes, this fixes autologin into wayland sessions.

**Comment by davidedmundson** [comment]
> Yes, this fixes autologin into wayland sessions.

Which bit? I can see we avoid calling displayServer->start() but that basically does nothing for x11-user or wayland setups.

**Comment by Vogtinator** [comment]
> > Yes, this fixes autologin into wayland sessions.
> 
> Which bit? I can see we avoid calling displayServer->start() but that basically does nothing for x11-user or wayland setups.

Correct, in case SDDM is configured to use rootful X11 still which is still the default.

Unless you want to drop rootful X11 as a bugfix, we need to address this somehow.

Ideally we'd address the root cause of the VT allocation issues somehow, but I don't know how (see #1896)

**Comment by davidedmundson** [comment]
>Unless you want to drop rootful X11 

I 1000% do. This code is already way too unmaintainable and it's unsafe for users. 

That said, I've done a code review. The other 4 cleanup commits are things we definitely want.

I'm at risk of spending longer discussing this than it would take to clean it up when the rootful X is dropped. 
If you think it's worth it, I'll press the button :)

>Ideally we'd address the root cause of the VT allocation issues somehow, but I don't know how (see https://github.com/sddm/sddm/pull/1896)

Ack.

**Review by davidedmundson — APPROVED** [review]

**Pull request merged**
