### PR TITLE
Add role needsPassword to UserModel and Change Maui theme to adapt

### PR DESCRIPTION
**Pull request by mobius3**
Added needsPassword role to UserModel by checking if current_pw->pw_password is empty.

Changed Maui to demonstrate how to use.

### CODE REVIEW

**Comment by leonardo2d** [comment]
This proposes a solution for issue #380

**Comment by jleclanche** [comment]
lgtm. thoughts @plfiorini

**Comment by plfiorini** [comment]
Fixing those nitpick issues myself when merging.

**Comment by plfiorini** [comment]
Merged

**Comment by mobius3** [comment]
Thanks!

**Pull request closed without merging**
