### PR TITLE
man: sddm.greeter.rst.in fix syntax error

### PR DESCRIPTION
**Pull request by Vincent43**
missing *

### CODE REVIEW

**Comment by abucodonosor** [comment]
It is alredy fixed in #908

**Comment by Vincent43** [comment]
Unless I'm missing something it's **introduced** in https://github.com/sddm/sddm/pull/908

**Comment by abucodonosor** [comment]
no :) v.0.16.0 was released with this typo .. #908 fix that and the rest of man files too

see https://github.com/sddm/sddm/pull/908/commits/9fa37aa334f4638c4f9946dc5f3e9d15973e553a for the typo fix

**Comment by abucodonosor** [comment]
@Vincent43 

argh .. yes sorry this one I introduced myself

**Pull request merged**
