### PR TITLE
Add X args

### PR DESCRIPTION
**Pull request by bjacquot**
add the possibility of adding parameters to the X server

### CODE REVIEW

**Comment by jleclanche** [comment]
What do you need this for, specifically?

**Comment by bjacquot** [comment]
I have a multiseat configuration for which I would manage only a seat with sddm. So I have to add an argument "-seat xxx"

**Comment by bjacquot** [comment]
Ok, done. Maybe the argument ServerArguments must be initialized with "-nolisten tcp -background none -noreset" and avoid them in XorgDisplayServer.cpp.

**Comment by plfiorini** [comment]
@jleclanche This might be needed to close #325

**Comment by plfiorini** [comment]
Squashed and merged

**Pull request closed without merging**
