### PR TITLE
Added Swedish as language

### PR DESCRIPTION
**Pull request by Umeaboy**
Signed-off-by: Kristoffer Grundström <hamnisdude@gmail.com>

### CODE REVIEW

**Comment by plfiorini** [comment]
Closing because it was already merge previously

**Comment by plfiorini** [comment]
actually not, @davidedmundson merge #662 and forgot to merge this one too :-/

**Comment by plfiorini** [comment]
Now it's merged, thanks @Umeaboy

**Comment by Umeaboy** [comment]
You're welcome!

**Pull request closed without merging**
