### PR TITLE
bump version to 0.20.0

### PR DESCRIPTION
**Pull request by hsitter**
in preparation of release

### CODE REVIEW

**Review by davidedmundson — APPROVED** [review]

**Comment by Vogtinator** [comment]
I guess we should create a formal issue for 0.20 tasks?

**Comment by hsitter** [comment]
Are there any tasks left for 0.20?

**Comment by Vogtinator** [comment]
The issue with kwin_wayland not starting properly half the time after a logout needs to be investigated at least.
Or running the greeter with wayland gets marked as experimental explicitly...

**Comment by Vogtinator** [comment]
> The issue with kwin_wayland not starting properly half the time after a logout needs to be investigated at least. Or running the greeter with wayland gets marked as experimental explicitly...

With that there's also the issue that keyboard layout switching is implemented wrongly (https://github.com/sddm/sddm/issues/1669)

**Comment by hsitter** [comment]
Started https://github.com/sddm/sddm/issues/1735 David and I are thinking that wayland support should probably be treated as experimental for its first release anyway.

**Comment by Pointedstick** [comment]
@sitter Agreed.

**Pull request merged**
