### PR TITLE
A couple of multi monitor fixes

### PR DESCRIPTION
**Pull request by plfiorini**
Trying to fix multi monitor support.

### CODE REVIEW

**Comment by plfiorini** [comment]
For some reason on all my systems, mirror mode kicks in and that doesn't help testing.
For future reference, I had to do this on Xsetup:
xrandr --output LVDS1 --auto --rotate normal --pos 0x0 --output VGA1 --auto --right-of LVDS1

**Comment by CMCDragonkai** [comment]
Does this show a login screen of every display? For some reason my primary screen is auto detected to not be my laptop screen, which is annoying.

**Comment by plfiorini** [comment]
Primary screen is detected by Xorg, SDDM uses whatever the display server tells it to use.

**Comment by CMCDragonkai** [comment]
Yea, so does it clone the login prompt to every display? That would be cool.

**Pull request merged**
