### PR TITLE
WIP: Wayland support for the greeter

### PR DESCRIPTION
**Pull request by plfiorini**

### CODE REVIEW

**Comment by plfiorini** [comment]
Status as of today: almost working

The socket presence check sucks and needs to be better written, maybe a QEventLoop and QFileSystemWatcher. Doing asynchronous code in a synchronous call is weird.

Managed to get the compositor up and running once but got an error when taking vt control. There are problems with weston too, so it's not the compositor's fault rather sddm.

**Comment by plfiorini** [comment]
Update: compositor and greeter start but libinput is not working, it's weird because it works with Wayland user sessions (even tested with Hawaii that uses the same compositor infrastructure). There is definitely something missing between sddm and logind.

Greeter needs a keyboard implementation for Wayland using xkbcommon.

**Comment by plfiorini** [comment]
Needs #673 first otherwise we won't be able to run X11 sessions from a Wayland greeter

**Comment by DeX77** [comment]
Any news on this? Seems like #673 is done so far?

**Comment by SparK-Cruz** [comment]
Still no wayland greeter?

**Comment by ericschdt** [comment]
It's on the TODO list of KDE: 

> sddm without X

 https://phabricator.kde.org/T11640 :)

**Comment by bam80** [comment]
Do we really need even Wayland here? I mean - can't the DM draw directly?

**Comment by soredake** [comment]
Any progress?

**Comment by plfiorini** [comment]
Contiuing on #1367

**Pull request closed without merging**
