### PR TITLE
PinkList

### PR DESCRIPTION
**Pull request by cloc3**
Greeter userlists are usefull in a lot of working environments, where people like
to be recognized by the system.

A good userlist needs an autocompletion feature.

A userlist with autocompetion feature was available in the old kdm 
displaymanger. Sddm is a replacement for kdm, so it should provide userlists 
with autocompletion.

Implementing the autocompletion feature is really easy, and may it be done 
using only few lines of qt preexisting code.

This pull request contain a theme, named "pinkList", which provide an example
of userlist for sddm, with the autocompletion feature.
we hope this may be welcome by the community.

waiting for your opinion,
marco and giulio.

### CODE REVIEW

**Comment by cloc3** [comment]
sorry.
this is first time I try to submit a pull request to a developing project, so
I don't know well how travis works.

In my system this sddm version with my patch builds correctly using a gentoo 
ebuild and works fine.

I've read the job log at this address:
https://travis-ci.org/sddm/sddm/jobs/319949263

nevertheless, I don't understand what is going wrong.
the only error lines are:

664 chsh: user "git" does not exist.
665 error: command failed to execute correctly
...
704 Inconsistency detected by ld.so: dl-open.c: 689: _dl_open: Assertion `_dl_debug_initialize (0, args.nsid)->r_state == RT_CONSISTENT' failed!

no one of these lines gives my any idea of what should I do to fix my problem.
may you please give me some help?

**Comment by plfiorini** [comment]
This seems ArchTravis going mental

**Comment by plfiorini** [comment]
Don't change the avatar icon also what do you need the old Qt logo for?

**Comment by cloc3** [comment]
Thank for your attention. I don't care about the choice for a particular logo.
I choose the old QT logo because I don't like funnies like cats or beaches.
In my mind, the official sddm screenshot should contain a specific sddm logo, but I think
 it doesn't exists yet.
My only goal is to implement the autocompletion feature. The logo may it be easily changed.

**Comment by plfiorini** [comment]
Authors disappeared

**Pull request closed without merging**
