### PR TITLE
sddm service is a part of graphical target

### PR DESCRIPTION
**Pull request by tpgxyz**
This allow to stop or restart sddm.service when graphical.target revices one of these signals.

### CODE REVIEW

**Comment by davidedmundson** [comment]
Intuitively I would agree it makes sense, my concern is that neither GDM nor LightDM do this and in general we want to be somewhat consistent.

I'll ping a GDM author.

**Comment by davidedmundson** [comment]
>I'll ping a GDM author.

"It makes sense, but probably also simply doesn't make a difference in practice"

Which I would also agree with, it's an odd thing to stop, but shouldn't do any harm in the general case

**Review by davidedmundson — APPROVED** [review]

**Comment by tpgxyz** [comment]
Guess other DM's are not aware of `PartOf`.
Anyways this introduces some consistency, so if I switch target, I'll not be left with any running services from my previous target.

**Comment by tpgxyz** [comment]
@davidedmundson @plfiorini Can you guys please merge this ?

**Pull request merged**
