### PR TITLE
Improvements to faces

### PR DESCRIPTION
**Pull request by jleclanche**

### CODE REVIEW

**Comment by plfiorini** [comment]
i'm not saying i'm against this just yet but could it be possible to improve performance of model population instead of adding yet another setting?

**Comment by plfiorini** [comment]
like concurrent population

**Comment by jleclanche** [comment]
@plfiorini See #274. I was against adding another setting, and I also think avatar loading should be done async, but I *also* think a setting to disable avatars altogether is reasonable which makes it a good compromise.

**Comment by jleclanche** [comment]
BTW the idea is to make the enableAvatars config public to themes so that they can use it to not show avatars at all. This is less urgent though.

**Comment by plfiorini** [comment]
ok gtm

**Comment by Seegras** [comment]
Trying to read the users home dir fails miserably if its encrypted (and automounted upon login of the user). So yes, there needs to be an option to inhibit sddm from trying to read /home and everything below.

**Pull request merged**
