### PR TITLE
Wip/clientlog

### PR DESCRIPTION
**Pull request by plfiorini**

### CODE REVIEW

**Comment by plfiorini** [comment]
i thought i have already sent this once and i remember you commenting it but i cannot find it anywhere.
so i'm just sending it another time.

**Comment by plfiorini** [comment]
just force pushed the last revision, seems to work now

**Comment by tuzonice** [comment]
Thanks. I’ll check that commit out, as soon as I can, though a Gentoo recompile is in the mean time (setting -fPIC globally on non-hardened is a very_bad_idea ;-) ).

**Comment by jleclanche** [comment]
Please add a ChangeLog entry, specify the new default values and gtm

**Comment by plfiorini** [comment]
@jleclanche commits have the ChangeLog tag just like Qt so we can automatically create change log files. We should always do so for important commits.

**Comment by jleclanche** [comment]
@plfiorini It's easier to generate the changelog as we go along, that way progress is visible for those looking at the git repo.

**Comment by plfiorini** [comment]
@jleclanche it can be done with another commit after, mixing code with other files seems bad and will screw up in case of a revert.

**Pull request closed without merging**
