### PR TITLE
Make sure greeter sessions are set with QT_NO_XDG_DESKTOP_PORTAL=1

### PR DESCRIPTION
**Pull request by aleixpol**
Other processes involved could also be triggering xdp

### CODE REVIEW

**Comment by Vogtinator** [comment]
Can be removed from `GreeterApp` itself now?

**Comment by aleasto** [comment]
Solves portal starting and crashing with sddm-wayland-plasma from fedora

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
> Can be removed from `GreeterApp` itself now?

I'd rather not, since this fix additively makes it work properly. There's no reason that the portal service should launch in SDDM ever anyway.

**Comment by geraldosimiao** [comment]
Hello friends, I tested the new sddm build. It fixes the problem with xdg-desktop-portal-kde crashes, but other behavior still present. I opened a ticket dowstream https://bugzilla.redhat.com/show_bug.cgi?id=2179998

**Comment by geraldosimiao** [comment]
Screencast from a updated F38 KDE.

[sddm-wayland-plasma-f38.webm](https://user-images.githubusercontent.com/72357821/226379506-16d452cb-a141-4ec0-b5d3-324e13481c21.webm)

**Comment by Conan-Kudo** [comment]
Please make a new ticket instead of piling in this PR.

**Comment by aleixpol** [comment]
> Can be removed from `GreeterApp` itself now?

It can, I'd removed it locally, I forgot to commit it with the changes. Thanks!

**Review by Vogtinator — APPROVED** [review]

**Pull request merged**
